/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package it.unicam.cs.pa.giocoScacchiera.app;


import it.unicam.cs.pa.giocoScacchiera.list.api.*;
import it.unicam.cs.pa.giocoScacchiera.list.lib.*;

public class App {
    public static void main(String[] args) {
        
        Giocatore g = new GiocatoreDama("LUCA", ColorePezzi.BIANCO);
        Gioco d = new GiocoDama(g,new GiocatoreDama("BOT",ColorePezzi.NERO));
        d.gameLoop();
    }
}
